#!/usr/bin/python

print ("Enter the amount:")
Princ = int(input())
print("Enter the rate of interest:")
RateOfInterest = int(input())
print("Enter the number of years:")
Years = int(input())
R = RateOfInterest / 100
print(R)
#amount = Princ + pow(((1 + (RateOfInterest / 100)), Years)
#print(amount)

